### PR TITLE
Fix stdune -> pp bound

### LINKED ISSUE #8657: stdune fails to build: Unbound value Pp.compare
Building stdune from the opam file yields the following error

```
#=== ERROR while compiling stdune.3.11.0~alpha1 ===============================#
# context              2.2.0~alpha3~dev | linux/x86_64 | ocaml-base-compiler.4.13.1 | pinned(https://github.com/ocaml/dune/releases/download/3.11.0_alpha1/dune-3.11.0.alpha1.tbz)
# path                 ~/.opam/4.13/.opam-switch/build/stdune.3.11.0~alpha1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p stdune -j 31 @install
# exit-code            1
# env-file             ~/.opam/log/stdune-7-4b7ddc.env
# output-file          ~/.opam/log/stdune-7-4b7ddc.out
### output ###
# (cd _build/default && /home/opam/.opam/4.13/bin/ocamlc.opt -w -40 -alert -unstable -g -bin-annot -I otherlibs/stdune/src/.stdune.objs/byte -I /home/opam/.opam/4.13/lib/csexp -I /home/opam/.opam/4.13/lib/dyn -I /home/opam/.opam/4.13/lib/ordering -I /home/opam/.opam/4.13/lib/pp -I otherlibs/stdune/dune_filesystem_stubs/.dune_filesystem_stubs.objs/byte -no-alias-deps -open Stdune__ -o otherlibs/stdune/src/.stdune.objs/byte/stdune.cmo -c -impl otherlibs/stdune/src/stdune.ml)
# File "otherlibs/stdune/src/stdune.ml", line 31, characters 21-31:
# 31 |     Ordering.of_int (Pp.compare (fun a b -> Ordering.to_int (compare a b)) x y)
#                           ^^^^^^^^^^
# Error: Unbound value Pp.compare
```

I bisected this to d4d7c00a2cce8fca1186929e97cfed9df98ddcfb.

### PR DESCRIPTION
**Pull request by emillon**
It uses `Pp.compare`, introduced in `pp.1.2.0`.

Fixes #8657

### CODE REVIEW

**Comment by emillon** [comment]
This will require https://github.com/ocaml/opam-repository/pull/24446.

**Review by rgrinberg — APPROVED** [review]

**Review by Alizter — APPROVED** [review]
