### PR TITLE
fix(fsevents): restore compat with older mac

### LINKED ISSUE #5430: Dune 3.0 doesn't compile on macOS older than 10.13
Building Dune on macOS < 10.13 results in the following compilation errors:

```
       last 10 log lines:
       >       kFSEventStreamCreateFlagUseExtendedData |
       >       ^
       > src/fsevents/fsevents_stubs.c:315:5: error: use of undeclared identifier 'kFSEventStreamEventFlagItemCloned'
       >     kFSEventStreamEventFlagItemCloned};
       >     ^
       > src/fsevents/fsevents_stubs.c:320:22: error: invalid application of 'sizeof' to an incomplete type 'const FSEventStreamEventFlags []'
       >   size_t len = sizeof(all_flags) / sizeof(FSEventStreamEventFlags);
       >                      ^~~~~~~~~~~
       > 4 errors generated.
```

It seems like these APIs are only part of the 10.13 SDK.

### PR DESCRIPTION
**Pull request by rgrinberg**
kFSEventStreamEventFlagItemCloned is introduced in 10.13

@anmonteiro could you test this?

### CODE REVIEW

**Comment by rgrinberg** [comment]
Thanks. I fixed those errors as well. Unfortunately this means that the native watch mode will not work pre 10.13.

**Comment by anmonteiro** [comment]
I can confirm this now fixes the macOS build failures I was seeing.

**Review by nojb — APPROVED** [review]
LGTM. Another possibility is to just #ifdef the whole file with `__MAC_OS_X_VERSION_MAX_ALLOWED >= 101300` and make all primitives fail if that condition is not satisfied.

**Comment by rgrinberg** [comment]
> LGTM. Another possibility is to just #ifdef the whole file with __MAC_OS_X_VERSION_MAX_ALLOWED >= 101300 and make all primitives fail if that condition is not satisfied.

Good point. Pushed a commit to do this.

**Comment by barracuda156** [comment]
@anmonteiro This does not suffice:
```
--->  Building ocaml-dune
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_ocaml_ocaml-dune/ocaml-dune/work/dune-3.6.0" && /usr/bin/make -j6 -w release 
make: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_ocaml_ocaml-dune/ocaml-dune/work/ocaml-dune-bf9eb75'
ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot unix.cma boot/libs.ml boot/duneboot.ml
./.duneboot.exe
cd _boot && /opt/local/bin/ocamlc -c -g -I +threads fsevents_stubs.c
src/fsevents/fsevents_stubs.c:67:5: error: 'kFSEventStreamEventFlagItemCreated' undeclared here (not in a function); did you mean 'kFSEventStreamEventFlagUserDropped'?
src/fsevents/fsevents_stubs.c:67:42: error: 'kFSEventStreamEventFlagItemRemoved' undeclared here (not in a function); did you mean 'kFSEventStreamEventFlagUserDropped'?
src/fsevents/fsevents_stubs.c:68:5: error: 'kFSEventStreamEventFlagItemRenamed' undeclared here (not in a function); did you mean 'kFSEventStreamEventFlagRootChanged'?
src/fsevents/fsevents_stubs.c:68:42: error: 'kFSEventStreamEventFlagItemModified' undeclared here (not in a function); did you mean 'kFSEventStreamEventFlagUserDropped'?
src/fsevents/fsevents_stubs.c: In function 'dune_fsevents_create':
src/fsevents/fsevents_stubs.c:160:44: error: 'kFSEventStreamCreateFlagFileEvents' undeclared (first use in this function); did you mean 'kFSEventStreamCreateFlagNoDefer'?
src/fsevents/fsevents_stubs.c:160:44: note: each undeclared identifier is reported only once for each function it appears in
src/fsevents/fsevents_stubs.c: In function 'dune_fsevents_set_exclusion_paths':
src/fsevents/fsevents_stubs.c:185:14: warning: implicit declaration of function 'FSEventStreamSetExclusionPaths' [-Wimplicit-function-declaration]
src/fsevents/fsevents_stubs.c: In function 'dune_fsevents_kind':
src/fsevents/fsevents_stubs.c:256:15: error: 'kFSEventStreamEventFlagItemIsDir' undeclared (first use in this function); did you mean 'kFSEventStreamEventFlagUnmount'?
src/fsevents/fsevents_stubs.c: At top level:
src/fsevents/fsevents_stubs.c:298:5: error: 'kFSEventStreamEventFlagItemInodeMetaMod' undeclared here (not in a function); did you mean 'kFSEventStreamEventFlagUserDropped'?
src/fsevents/fsevents_stubs.c:301:5: error: 'kFSEventStreamEventFlagItemFinderInfoMod' undeclared here (not in a function); did you mean 'kFSEventStreamEventFlagKernelDropped'?
src/fsevents/fsevents_stubs.c:302:5: error: 'kFSEventStreamEventFlagItemChangeOwner' undeclared here (not in a function); did you mean 'kFSEventStreamEventFlagRootChanged'?
src/fsevents/fsevents_stubs.c:303:5: error: 'kFSEventStreamEventFlagItemXattrMod' undeclared here (not in a function); did you mean 'kFSEventStreamEventFlagUnmount'?
src/fsevents/fsevents_stubs.c:304:5: error: 'kFSEventStreamEventFlagItemIsFile' undeclared here (not in a function); did you mean 'kFSEventStreamEventFlagUnmount'?
src/fsevents/fsevents_stubs.c:305:5: error: 'kFSEventStreamEventFlagItemIsDir' undeclared here (not in a function); did you mean 'kFSEventStreamEventFlagUnmount'?
src/fsevents/fsevents_stubs.c:306:5: error: 'kFSEventStreamEventFlagItemIsSymlink' undeclared here (not in a function); did you mean 'kFSEventStreamEventFlagUnmount'?
src/fsevents/fsevents_stubs.c:307:5: error: 'kFSEventStreamEventFlagOwnEvent' undeclared here (not in a function); did you mean 'kFSEventStreamEventFlagUnmount'?
src/fsevents/fsevents_stubs.c:308:5: error: 'kFSEventStreamEventFlagItemIsHardlink' undeclared here (not in a function); did you mean 'kFSEventStreamEventFlagHistoryDone'?
src/fsevents/fsevents_stubs.c:309:5: error: 'kFSEventStreamEventFlagItemIsLastHardlink' undeclared here (not in a function); did you mean 'kFSEventStreamEventFlagHistoryDone'?
make: *** [_boot/dune.exe] Error 2
```

**Comment by barracuda156** [comment]
@rgrinberg @anmonteiro I.e. all those are 10.7 up: http://pike.lysator.liu.se/generated/manual/modref/ex/predef_3A_3A/System/FSEvents.html

**Comment by barracuda156** [comment]
Ah, wait a minute, you fix is just not there in 3.6.0. I am sorry, should have not taken it for granted. Gonna add a patch.
