### ISSUE TITLE
`dune build` over RPC reports diagnostics twice

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#15609]
Starting an eager watch sever in the background and doing `dune build` reports doubled diagnostics:

```
$ dune build
File "/home/ali/dune5/src/memo/node.ml", line 401, characters 13-14:
401 |     | [] -> (x)
                   ^
Unbound value x
File "/home/ali/dune5/src/memo/node.ml", line 401, characters 13-14:
401 |     | [] -> (x)
                   ^
Unbound value x
Error: Build failed with 2 errors.                   
```

The same does not happen with passive watch mode.

**Comment by Alizter** [comment]
This issue doesn't appear to be present in 3.24.1.

**Comment by Alizter** [comment]
Bisected to #15191
