### PR TITLE
fix(cross): expand artifacts in the right context

### LINKED ISSUE #9199: cross-compilation regression on mirage
Our mirage CI run is broken. The linking step fails with:

```
/usr/bin/ld: /home/runner/work/dune/dune/mirage/_build/solo5/duniverse/Zarith/../../../install/default/lib/gmp//libgmp.a(assert.o): in function `__gmp_assert_header':
assert.c:(.text+0x36): undefined reference to `__fprintf_chk'
/usr/bin/ld: /home/runner/work/dune/dune/mirage/_build/solo5/duniverse/Zarith/../../../install/default/lib/gmp//libgmp.a(assert.o): in function `__gmp_assert_fail':
assert.c:(.text+0x9a): undefined reference to `__fprintf_chk'
/usr/bin/ld: /home/runner/work/dune/dune/mirage/_build/solo5/duniverse/Zarith/../../../install/default/lib/gmp//libgmp.a(assert.o): in function `__gmp_assert_header':
assert.c:(.text+0x6c): undefined reference to `__fprintf_chk'
/usr/bin/ld: /home/runner/work/dune/dune/mirage/_build/solo5/duniverse/Zarith/../../../install/default/lib/gmp//libgmp.a(memory.o): in function `__gmp_default_allocate':
memory.c:(.text+0x42): undefined reference to `__fprintf_chk'
/usr/bin/ld: /home/runner/work/dune/dune/mirage/_build/solo5/duniverse/Zarith/../../../install/default/lib/gmp//libgmp.a(memory.o): in function `__gmp_default_reallocate':
memory.c:(.text+0x95): undefined reference to `__fprintf_chk'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
```

I bisected that to #8740. I'll try to isolate a repro case.

### PR DESCRIPTION
**Pull request by emillon**
Fixes #9199

### CODE REVIEW

**Comment by emillon** [comment]
Not 100% sure it's the right fix but it fixes the test.

**Review by rgrinberg — APPROVED** [review]

**Comment by rgrinberg** [comment]
Fix looks good to me.
