### ISSUE TITLE
3.23.0 broke SmartOS build

### ISSUE THREAD

**Issue by 0-wiz-0** [ocaml/dune#14530]
## Expected Behavior
3.23.0 building on Illumos.

## Actual Behavior
After updating dune in pkgsrc from 3.22.2 to 3.23.0, the build on a bulk build machines running SmartOS broke, see https://reports.pkgci.org/SmartOS/upstream/trunk/20260513T220202Z/ocaml-dune-3.23.0/build.log
```
cd _boot && /tmp/work/devel/ocaml-dune/work/.buildlink/bin/ocamlopt.opt -c -g -I +threads time_stubs.c
otherlibs/stdune/src/time_stubs.c: In function 'dune_time_stat_mtime_ns':
otherlibs/stdune/src/time_stubs.c:51:35: error: '_timestruc_t' {aka 'const struct _timespec'} has no member named 'tv_sec'; did you mean '__tv_sec'?
otherlibs/stdune/src/time_stubs.c:52:36: error: '_timestruc_t' {aka 'const struct _timespec'} has no member named 'tv_nsec'; did you mean '__tv_nsec'?
gmake: *** [Makefile:43: _boot/dune.exe] Error 2
```
## Reproduction

try building on SmartOS

## Specifications

- Version of `dune` (output of `dune --version`): 3.23.0
- Version of `ocaml` (output of `ocamlc --version`): 4.14.3
- Operating system (distribution and version): SmartOS x86_64

I have no access to a SmartOS machine myself, but pkgsrc is cross-platform. I hope that you'll have an idea how to fix this.

**Comment by Alizter** [comment]
If you submit a patch, we can consider it, but we only support Linux, MacOS, and Windows. The other BSDs and even Haiku only work because users have been kind enough to submit patches. I am not familiar with SmartOS myself, so I wouldn't know what would need to be patched nor would I know how to test it.
