### ISSUE TITLE
Failure compiling dune.2.7.1 on windows with ocaml.4.11.0

### ISSUE THREAD

**Issue by KeenWill** [ocaml/dune#3840]
## Compilation Error

```
#=== ERROR while compiling dune.2.7.1 =========================================#
# context              2.0.7 | win32/x86_64 | ocaml-variants.4.11.0+mingw64c | git+https://github.com/fdopen/opam-repository-mingw.git#opam2
# path                 ~/.opam/ocaml-variants.4.11.0+mingw64c/.opam-switch/build/dune.2.7.1
# command              C:\cygwin\home\runneradmin\.opam\ocaml-variants.4.11.0+mingw64c\bin\ocaml.exe bootstrap.ml -j 3
# exit-code            2
# env-file             ~/.opam/log/dune-1688-487456.env
# output-file          ~/.opam/log/dune-1688-487456.out
### output ###
# [...]
# ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot unix.cma boot/libs.ml boot/duneboot.ml
# In file included from /home/runneradmin/.opam/ocaml-variants.4.11.0+mingw64c/lib/ocaml/caml/mlvalues.h:23,
#                  from C:\cygwin\tmp\camlobj240f10.c:6:
# /home/runneradmin/.opam/ocaml-variants.4.11.0+mingw64c/lib/ocaml/caml/misc.h:409:18: error: static declaration of 'caml_snprintf' follows non-static declaration
#   409 | #define snprintf caml_snprintf
#       |                  ^~~~~~~~~~~~~
# /home/runneradmin/.opam/ocaml-variants.4.11.0+mingw64c/lib/ocaml/caml/misc.h:408:12: note: previous declaration of 'caml_snprintf' was here
#   408 | extern int caml_snprintf(char * buf, size_t size, const char * format, ...);
#       |            ^~~~~~~~~~~~~
# ** Fatal error: Error while compiling
# File "boot/duneboot.ml", line 1:
# Error: Error while building custom runtime system
```

## Reproduction

Failure can be seen here in a PR in my own project [Camelot](https://github.com/upenn-cis1xx/camelot/pull/70/checks?check_run_id=1195196846) that has dune as a dependency.

Camelot requires dune >= v2.5. When installing using `opam install . --deps-only --with-test --with-doc`, it fails when installing dune with the error above. It is running on github actions' windows agent with ocaml compiler version 4.11.0. It is the only ocaml / OS combination that fails (4.11.0 works on ubuntu, 4.10.1 works on windows, etc).

## Specifications

- Dune 2.7.1
- Ocaml 4.11.0
- Windows Github Actions Agent

**Comment by nojb** [comment]
This is an OCaml problem, not a `dune` one: see https://github.com/ocaml/ocaml/issues/9938

**Comment by nojb** [comment]
Closing this for now as it is not `dune`-related.
