### PR TITLE
Remove `Mutex`

### LINKED ISSUE #11450: ci: regular failure of 4 tests
Since the introduction of #11302, some tests seem to fail with the following errors:
```
Unbound module Mutex
```
This PR indeed introduces a call to a `Mutex` module in _vendor/opam-file-format_.

This issue concerns the following tests:
- Coq 8.16.1
- Wasm_of_ocaml
- Build monorepo benchmark docker image
- Build (ocaml-base-compiler.4.14.2,system-msvc, windows-latest

The common thing is that they all worked on `4.14.X`. However, I have check [in the manual](https://ocaml.org/manual/4.14/api/Mutex.html), the `module Mutex` is available.

Does it require to be added to the deps as Unix for this version? Any ideas about this @Leonidas-from-XIV, @gridbugs and @rgrinberg?

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
As discussed in #11451 this removes the mutex that was added in #11302.

Fixes #11450
Fixes #11451

### CODE REVIEW

**Review by maiste — APPROVED** [review]
LGTM! Thanks 😊 Feel free to close the other PR.

**Comment by Leonidas-from-XIV** [comment]
That should happen automatically when this is merged due to the `Fixes` lines.
