### ISSUE TITLE
Dune 3.0 doesn't compile on macOS older than 10.13

### ISSUE THREAD

**Issue by anmonteiro** [ocaml/dune#5430]
Building Dune on macOS < 10.13 results in the following compilation errors:

```
       last 10 log lines:
       >       kFSEventStreamCreateFlagUseExtendedData |
       >       ^
       > src/fsevents/fsevents_stubs.c:315:5: error: use of undeclared identifier 'kFSEventStreamEventFlagItemCloned'
       >     kFSEventStreamEventFlagItemCloned};
       >     ^
       > src/fsevents/fsevents_stubs.c:320:22: error: invalid application of 'sizeof' to an incomplete type 'const FSEventStreamEventFlags []'
       >   size_t len = sizeof(all_flags) / sizeof(FSEventStreamEventFlags);
       >                      ^~~~~~~~~~~
       > 4 errors generated.
```

It seems like these APIs are only part of the 10.13 SDK.

**Comment by anmonteiro** [comment]
fixed by #5431
