### ISSUE TITLE
@ocaml-index fails when multiple executables in a directory don't specify (modules)

### ISSUE THREAD

**Issue by samoht** [ocaml/dune#13566]
When a directory contains multiple (executable) or (test) stanzas without explicit (modules) fields, dune includes all .ml files in each executable. This works for normal builds because each executable is compiled independently with its own library dependencies.

However, @ocaml-index appears to process modules in a way that doesn't respect the per-executable library dependencies. If executable A depends on alcotest and executable B doesn't, but both include foo.ml (which uses Alcotest), the index build fails with "Unbound module Alcotest" when processing foo.ml in the context of executable B.

Minimal reproduction:
```
# test/dune
(executable
   (name foo)
   (libraries alcotest))

(executable
   (name bar)
   (libraries unix))
```

```ocaml
(* test/foo.ml *)
let () = Alcotest.(check int) "test" 1 1
```

```ocaml
(* test/bar.ml *)
let () = print_endline "hello"
```
Running dune build @ocaml-index fails because foo.ml gets included in the bar executable's module set, and when the indexer processes it there, Alcotest is not available.

Workaround: Add explicit (modules foo) and (modules bar) to each stanza.

Expected behavior:

@ocaml-index should either:
1. Respect library dependencies when indexing modules for each executable, or
2. Only index modules that are actually part of each executable's dependency graph

**Comment by Alizter** [comment]
@voodoos What do you think the correct behaviour should be here? It's not so clear to me what the best thing to do is.

**Comment by Alizter** [comment]
I've managed to fix this issue by going through 2. I've got a reproduction case in #13587 and a follow up fix.

**Comment by voodoos** [comment]
> I've managed to fix this issue by going through 2. I've got a reproduction case in https://github.com/ocaml/dune/pull/13587 and a follow up fix.

I think that is the correct way to go indeed. Ideally `@ocaml-index` would only index the modules implicated in the current build, that a long overdue improvement.

**Comment by voodoos** [comment]
More context relative to the treatment of this issue: https://github.com/ocaml/dune/pull/13644#issuecomment-3945146496

It was concluded that the real bug here is that Dune should not allow users to share modules between distinct executable stanzas, as it is the case already for libraries.

**Comment by robinbb** [comment]
My read of this thread, and the closing comments on #12451 / the review on #13644, is that the maintainer consensus is "the real fix is to forbid module-sharing between exe stanzas, with enabled_if-aware semantics." This is reiterated by @voodoos here.

If it's useful, I'd be happy to take a pass at reviving #12451 with enabled_if handling. I don't want to step on @Alizter's toes if the work is in-progress, however, or if I have misunderstood the consensus on the right solution.

**Comment by Alizter** [comment]
@robinbb I am not currently actively working on this so please feel free to take over.

Enabled_if is one of the things that need to be considered, the other is how to guard this behind dune lang so that older projects relying on this behaviour don't fail to build with a newer dune until the project lang is bumped.
