### ISSUE TITLE
Missing -I when building against a virtual library from another project

### ISSUE THREAD

**Issue by rlepigre** [ocaml/dune#3636]
I am having a weird issue with a library containing a bunch of `modules` and one `virtual_modules`.
(The problem arises both with `dune.2.0.1` and `dune 2.6.1`, I have not tried other versions.)

First, when the library is installed, no `.cma` or `.cmxa` files are installed by dune, and the `META` file has empty fields:
```
package "my_lib" (
  ...
  archive(byte) = ""
  archive(native) = ""
  plugin(byte) = ""
  plugin(native) = ""
)
```
Is that expected behaviour? I could find no clear explanation about that in the doc.

Second, and that is really the origin of my problem, when I try to compile another project depending on the virtual library, no corresponding `-I` option is generated. I am currently working around that using:
```
 (flags (:standard -I +../my_package/my_lib)) ; FIXME crazy hack.
```
with which everything works as expected. However, I feel like I should not have to do that, and my fix is really fragile due to the explicit path.

Unfortunately I cannot give access to the sources of the project (it is not currently open-source, and I am not sure how much information I can give about it). However, here is what the dune file of the library looks like (it is used by other libraries and executables of the same project):
```
; The library containing a virtual module
(library
 (name my_lib)
 (public_name my_package.my_lib)
 (synopsis "...")
 (modules :standard)
 (virtual_modules virtual)
 (libraries ...))
```
And here is what the dune file of the (independent) project trying to use the library looks like:
```
; The executable trying to use the library with the virtual module
(executable
 (name main)
 (public_name my_program)
 (package my_other_package)
 (flags (:standard -w -27 -I +../my_package/my_lib)) ; FIXME crazy hack.
 (libraries cmdliner str unix ... my_package.my_lib my_package.impl_of_virt))
```

**Comment by jeremiedimino** [comment]
For the `META` file, yes that's expected. It's because at the moment `ocamlfind` doesn't support virtual libraries. For the `-I`, that is very suspicious indeed and you are right that it is not something you should do.

What does dune output when you don't add this `-I`?

**Comment by rlepigre** [comment]
OK, thanks, that makes sense.

The output is the following:
```
File "my_dir/file.ml", line 1, characters 5-18:
Error: Unbound module My_module
File "my_dir/file.mli", line 3, characters 41-76:
Error: Unbound module My_module
```

**Comment by jeremiedimino** [comment]
That's really odd. It looks like a standard use case of virtual libraries. However, it's a bit difficult for us to investigate without a minimal reproduction case. :(

**Comment by rlepigre** [comment]
Yeah, that is annoying. In fact, luckily,  I can now produce a reproduction case since a publicly available version of the library we are using has become available today here: https://github.com/rems-project/cerberus. You just need to pin it with:
```bash
opam pin add -y cerberus git+https://github.com/rems-project/cerberus.git
```
(I know for sure this works with OCaml 4.07.1.)

The file [buggy.tar.gz](https://github.com/ocaml/dune/files/4955076/buggy.tar.gz) contains a minimal example to reproduce the problem, you can comment/uncomment the hackish fix in the `dune` file.

**Comment by jeremiedimino** [comment]
Thanks for sending a minimal example. @rgrinberg could you have a look at this?

**Comment by rgrinberg** [comment]
@rlepigre could you check if it's still an issue in 2.7? I'm unable to reproduce this with the latest version of dune.

**Comment by rlepigre** [comment]
Yes, I can reproduce with dune 2.7 (and the example from the archive linked above).
```
$> dune --version
2.7.0
$> dune build
File "main.ml", line 1, characters 5-18:
Error: Unbound module Cerb_frontend
```

What version of OCaml are you using?

**Comment by rlepigre** [comment]
Actually I forgot to recompile the library with the new version. I'll do that later and tell you if that does the trick.

**Comment by rgrinberg** [comment]
Could you try out `master` as well?

**Comment by rlepigre** [comment]
Yep, still fails with version `2.7.0-69-g1f3c32801`.

Note however that with this version of dune the package I depend on must be fixed slightly, by adding a dependency to the `result` package in `backend/driver/dune`. I guess this is due to a bug fix in dune, since my package should never have been able to depend on `result` without an explicit dependency.

**Comment by rgrinberg** [comment]
I see. Could you show the contents of your `dune-package` file of the `cerb` package? It should be either in the `_build` directory or installed in `~/.opam/<switch>/lib/...`

**Comment by rlepigre** [comment]
Here it is:
```
(lang dune 2.7)
(name cerberus)
(version da87de0)
(library
 (name cerberus.backend_common)
 (kind normal)
 (synopsis "Cerberus backend utilities")
 (archives
  (byte backend_common/cerb_backend.cma)
  (native backend_common/cerb_backend.cmxa))
 (plugins
  (byte backend_common/cerb_backend.cma)
  (native backend_common/cerb_backend.cmxs))
 (foreign_objects backend_common/cerberus_cstubs.o)
 (foreign_archives backend_common/libcerb_backend_stubs.a)
 (native_archives backend_common/cerb_backend.a)
 (requires
  cerberus.frontend
  cerberus.core_parser
  cerberus.c_parser
  pprint
  cerberus.util
  z3)
 (main_module_name Cerb_backend)
 (modes byte native)
 (modules
  (wrapped
   (main_module_name Cerb_backend)
   (modules
    ((name Auxl) (obj_name cerb_backend__Auxl) (visibility public) (impl))
    ((name Dot) (obj_name cerb_backend__Dot) (visibility public) (impl))
    ((name Exhaustive_driver)
     (obj_name cerb_backend__Exhaustive_driver)
     (visibility public)
     (impl)
     (intf))
    ((name Fs_ocaml)
     (obj_name cerb_backend__Fs_ocaml)
     (visibility public)
     (impl))
    ((name Pipeline)
     (obj_name cerb_backend__Pipeline)
     (visibility public)
     (impl)
     (intf)))
   (alias_module
    (name Cerb_backend)
    (obj_name cerb_backend)
    (visibility public)
    (kind alias)
    (impl))
   (wrapped true))))
(library
 (name cerberus.c_parser)
 (kind normal)
 (synopsis "C parser")
 (archives (byte c_parser/c_parser.cma) (native c_parser/c_parser.cmxa))
 (plugins (byte c_parser/c_parser.cma) (native c_parser/c_parser.cmxs))
 (native_archives c_parser/c_parser.a)
 (requires cerberus.frontend)
 (modes byte native)
 (modules
  (unwrapped
   ((name C_lexer) (obj_name c_lexer) (visibility public) (impl))
   ((name C_parser) (obj_name c_parser) (visibility public) (impl) (intf))
   ((name C_parser_driver)
    (obj_name c_parser_driver)
    (visibility public)
    (impl))
   ((name Lexer_feedback)
    (obj_name lexer_feedback)
    (visibility public)
    (impl)
    (intf))
   ((name Tokens) (obj_name tokens) (visibility public) (impl)))))
(library
 (name cerberus.core_parser)
 (kind normal)
 (synopsis "Core parser")
 (archives
  (byte core_parser/core_parser.cma)
  (native core_parser/core_parser.cmxa))
 (plugins
  (byte core_parser/core_parser.cma)
  (native core_parser/core_parser.cmxs))
 (native_archives core_parser/core_parser.a)
 (requires cerberus.frontend)
 (modes byte native)
 (modules
  (unwrapped
   ((name Core_lexer) (obj_name core_lexer) (visibility public) (impl))
   ((name Core_parser)
    (obj_name core_parser)
    (visibility public)
    (impl)
    (intf))
   ((name Core_parser_driver)
    (obj_name core_parser_driver)
    (visibility public)
    (impl))
   ((name Core_parser_util)
    (obj_name core_parser_util)
    (visibility public)
    (impl)))))
(library
 (name cerberus.frontend)
 (kind normal)
 (virtual)
 (synopsis "Cerberus frontend")
 (native_archives frontend/cerb_frontend.a)
 (requires lem pprint cerberus.util cerberus.sibylfs)
 (main_module_name Cerb_frontend)
 (modes byte native)
 (modules
  (wrapped
   (main_module_name Cerb_frontend)
   (modules
    ((name AilSyntax)
     (obj_name cerb_frontend__AilSyntax)
     (visibility public)
     (impl))
    ((name AilSyntaxAux)
     (obj_name cerb_frontend__AilSyntaxAux)
     (visibility public)
     (impl))
    ((name AilTypesAux)
     (obj_name cerb_frontend__AilTypesAux)
     (visibility public)
     (impl))
    ((name AilTyping)
     (obj_name cerb_frontend__AilTyping)
     (visibility public)
     (impl))
    ((name AilWf) (obj_name cerb_frontend__AilWf) (visibility public) (impl))
    ((name Annot) (obj_name cerb_frontend__Annot) (visibility public) (impl))
    ((name Any) (obj_name cerb_frontend__Any) (visibility public) (impl))
    ((name Ast_core)
     (obj_name cerb_frontend__Ast_core)
     (visibility public)
     (impl))
    ((name Bimap) (obj_name cerb_frontend__Bimap) (visibility public) (impl))
    ((name Boot) (obj_name cerb_frontend__Boot) (visibility public) (impl))
    ((name Boot_printf)
     (obj_name cerb_frontend__Boot_printf)
     (visibility public)
     (impl)
     (intf))
    ((name Builtins)
     (obj_name cerb_frontend__Builtins)
     (visibility public)
     (impl))
    ((name Cabs) (obj_name cerb_frontend__Cabs) (visibility public) (impl))
    ((name Cabs_to_ail)
     (obj_name cerb_frontend__Cabs_to_ail)
     (visibility public)
     (impl))
    ((name Cabs_to_ail_aux)
     (obj_name cerb_frontend__Cabs_to_ail_aux)
     (visibility public)
     (impl))
    ((name Cabs_to_ail_effect)
     (obj_name cerb_frontend__Cabs_to_ail_effect)
     (visibility public)
     (impl))
    ((name Cmm_aux)
     (obj_name cerb_frontend__Cmm_aux)
     (visibility public)
     (impl))
    ((name Cmm_csem)
     (obj_name cerb_frontend__Cmm_csem)
     (visibility public)
     (impl))
    ((name Cmm_op)
     (obj_name cerb_frontend__Cmm_op)
     (visibility public)
     (impl))
    ((name Constraint)
     (obj_name cerb_frontend__Constraint)
     (visibility public)
     (impl))
    ((name Core) (obj_name cerb_frontend__Core) (visibility public) (impl))
    ((name Core_anormalise)
     (obj_name cerb_frontend__Core_anormalise)
     (visibility public)
     (impl))
    ((name Core_aux)
     (obj_name cerb_frontend__Core_aux)
     (visibility public)
     (impl))
    ((name Core_ctype_aux)
     (obj_name cerb_frontend__Core_ctype_aux)
     (visibility public)
     (impl))
    ((name Core_eval)
     (obj_name cerb_frontend__Core_eval)
     (visibility public)
     (impl))
    ((name Core_indet)
     (obj_name cerb_frontend__Core_indet)
     (visibility public)
     (impl))
    ((name Core_linking)
     (obj_name cerb_frontend__Core_linking)
     (visibility public)
     (impl))
    ((name Core_peval)
     (obj_name cerb_frontend__Core_peval)
     (visibility public)
     (impl))
    ((name Core_remove_unused_functions)
     (obj_name cerb_frontend__Core_remove_unused_functions)
     (visibility public)
     (impl))
    ((name Core_rewrite)
     (obj_name cerb_frontend__Core_rewrite)
     (visibility public)
     (impl))
    ((name Core_rewriter)
     (obj_name cerb_frontend__Core_rewriter)
     (visibility public)
     (impl))
    ((name Core_run)
     (obj_name cerb_frontend__Core_run)
     (visibility public)
     (impl))
    ((name Core_run_aux)
     (obj_name cerb_frontend__Core_run_aux)
     (visibility public)
     (impl))
    ((name Core_sequentialise)
     (obj_name cerb_frontend__Core_sequentialise)
     (visibility public)
     (impl))
    ((name Core_typing)
     (obj_name cerb_frontend__Core_typing)
     (visibility public)
     (impl))
    ((name Core_typing_aux)
     (obj_name cerb_frontend__Core_typing_aux)
     (visibility public)
     (impl))
    ((name Core_typing_effect)
     (obj_name cerb_frontend__Core_typing_effect)
     (visibility public)
     (impl))
    ((name Core_unstruct)
     (obj_name cerb_frontend__Core_unstruct)
     (visibility public)
     (impl))
    ((name Ctype) (obj_name cerb_frontend__Ctype) (visibility public) (impl))
    ((name Debug) (obj_name cerb_frontend__Debug) (visibility public) (impl))
    ((name Decode)
     (obj_name cerb_frontend__Decode)
     (visibility public)
     (impl))
    ((name Decode_ocaml)
     (obj_name cerb_frontend__Decode_ocaml)
     (visibility public)
     (impl))
    ((name Defacto_memory)
     (obj_name cerb_frontend__Defacto_memory)
     (visibility public)
     (impl))
    ((name Defacto_memory_aux)
     (obj_name cerb_frontend__Defacto_memory_aux)
     (visibility public)
     (impl))
    ((name Defacto_memory_types)
     (obj_name cerb_frontend__Defacto_memory_types)
     (visibility public)
     (impl))
    ((name Dlist) (obj_name cerb_frontend__Dlist) (visibility public) (impl))
    ((name Driver)
     (obj_name cerb_frontend__Driver)
     (visibility public)
     (impl))
    ((name Enum) (obj_name cerb_frontend__Enum) (visibility public) (impl))
    ((name ErrorMonad)
     (obj_name cerb_frontend__ErrorMonad)
     (visibility public)
     (impl))
    ((name Errors)
     (obj_name cerb_frontend__Errors)
     (visibility public)
     (impl))
    ((name Exception)
     (obj_name cerb_frontend__Exception)
     (visibility public)
     (impl))
    ((name Exception_undefined)
     (obj_name cerb_frontend__Exception_undefined)
     (visibility public)
     (impl))
    ((name Float) (obj_name cerb_frontend__Float) (visibility public) (impl))
    ((name Fs) (obj_name cerb_frontend__Fs) (visibility public) (impl))
    ((name GenTypes)
     (obj_name cerb_frontend__GenTypes)
     (visibility public)
     (impl))
    ((name GenTypesAux)
     (obj_name cerb_frontend__GenTypesAux)
     (visibility public)
     (impl))
    ((name GenTyping)
     (obj_name cerb_frontend__GenTyping)
     (visibility public)
     (impl))
    ((name Global)
     (obj_name cerb_frontend__Global)
     (visibility public)
     (impl))
    ((name Impl_mem)
     (obj_name cerb_frontend__Impl_mem)
     (visibility public)
     (kind virtual)
     (intf))
    ((name Implementation)
     (obj_name cerb_frontend__Implementation)
     (visibility public)
     (impl))
    ((name IntegerImpl)
     (obj_name cerb_frontend__IntegerImpl)
     (visibility public)
     (impl))
    ((name Linux) (obj_name cerb_frontend__Linux) (visibility public) (impl))
    ((name Loc) (obj_name cerb_frontend__Loc) (visibility public) (impl))
    ((name Mem) (obj_name cerb_frontend__Mem) (visibility public) (impl))
    ((name Mem_aux)
     (obj_name cerb_frontend__Mem_aux)
     (visibility public)
     (impl))
    ((name Mem_common)
     (obj_name cerb_frontend__Mem_common)
     (visibility public)
     (impl))
    ((name Memory_model)
     (obj_name cerb_frontend__Memory_model)
     (visibility public)
     (impl))
    ((name Monadic_parsing)
     (obj_name cerb_frontend__Monadic_parsing)
     (visibility public)
     (impl))
    ((name Mucore)
     (obj_name cerb_frontend__Mucore)
     (visibility public)
     (impl))
    ((name Mucore_to_core)
     (obj_name cerb_frontend__Mucore_to_core)
     (visibility public)
     (impl))
    ((name Multiset)
     (obj_name cerb_frontend__Multiset)
     (visibility public)
     (impl))
    ((name Nondeterminism)
     (obj_name cerb_frontend__Nondeterminism)
     (visibility public)
     (impl))
    ((name Ocaml_gcc_builtins)
     (obj_name cerb_frontend__Ocaml_gcc_builtins)
     (visibility public)
     (impl))
    ((name Ocaml_implementation)
     (obj_name cerb_frontend__Ocaml_implementation)
     (visibility public)
     (impl))
    ((name Output)
     (obj_name cerb_frontend__Output)
     (visibility public)
     (impl))
    ((name Pp) (obj_name cerb_frontend__Pp) (visibility public) (impl))
    ((name Pp_ail)
     (obj_name cerb_frontend__Pp_ail)
     (visibility public)
     (impl)
     (intf))
    ((name Pp_ail_ast)
     (obj_name cerb_frontend__Pp_ail_ast)
     (visibility public)
     (impl))
    ((name Pp_ail_raw)
     (obj_name cerb_frontend__Pp_ail_raw)
     (visibility public)
     (impl))
    ((name Pp_ast)
     (obj_name cerb_frontend__Pp_ast)
     (visibility public)
     (impl))
    ((name Pp_cabs)
     (obj_name cerb_frontend__Pp_cabs)
     (visibility public)
     (impl)
     (intf))
    ((name Pp_core)
     (obj_name cerb_frontend__Pp_core)
     (visibility public)
     (impl)
     (intf))
    ((name Pp_core_ctype)
     (obj_name cerb_frontend__Pp_core_ctype)
     (visibility public)
     (impl))
    ((name Pp_defacto_memory)
     (obj_name cerb_frontend__Pp_defacto_memory)
     (visibility public)
     (impl)
     (intf))
    ((name Pp_errors)
     (obj_name cerb_frontend__Pp_errors)
     (visibility public)
     (impl))
    ((name Pp_mem)
     (obj_name cerb_frontend__Pp_mem)
     (visibility public)
     (impl)
     (intf))
    ((name Pp_mucore)
     (obj_name cerb_frontend__Pp_mucore)
     (visibility public)
     (impl))
    ((name Pp_run)
     (obj_name cerb_frontend__Pp_run)
     (visibility public)
     (impl))
    ((name Pp_std)
     (obj_name cerb_frontend__Pp_std)
     (visibility public)
     (impl))
    ((name Pp_symbol)
     (obj_name cerb_frontend__Pp_symbol)
     (visibility public)
     (impl)
     (intf))
    ((name Pp_trace)
     (obj_name cerb_frontend__Pp_trace)
     (visibility public)
     (impl))
    ((name Pp_utils)
     (obj_name cerb_frontend__Pp_utils)
     (visibility public)
     (impl))
    ((name Product)
     (obj_name cerb_frontend__Product)
     (visibility public)
     (impl))
    ((name Range) (obj_name cerb_frontend__Range) (visibility public) (impl))
    ((name Remove_unspecs)
     (obj_name cerb_frontend__Remove_unspecs)
     (visibility public)
     (impl))
    ((name Scope_table)
     (obj_name cerb_frontend__Scope_table)
     (visibility public)
     (impl))
    ((name Smt2) (obj_name cerb_frontend__Smt2) (visibility public) (impl))
    ((name State) (obj_name cerb_frontend__State) (visibility public) (impl))
    ((name State_exception)
     (obj_name cerb_frontend__State_exception)
     (visibility public)
     (impl))
    ((name State_exception_undefined)
     (obj_name cerb_frontend__State_exception_undefined)
     (visibility public)
     (impl))
    ((name Std) (obj_name cerb_frontend__Std) (visibility public) (impl))
    ((name String_ail)
     (obj_name cerb_frontend__String_ail)
     (visibility public)
     (impl))
    ((name String_cabs)
     (obj_name cerb_frontend__String_cabs)
     (visibility public)
     (impl))
    ((name String_core)
     (obj_name cerb_frontend__String_core)
     (visibility public)
     (impl))
    ((name String_core_ctype)
     (obj_name cerb_frontend__String_core_ctype)
     (visibility public)
     (impl))
    ((name String_core_run)
     (obj_name cerb_frontend__String_core_run)
     (visibility public)
     (impl))
    ((name String_defacto_memory)
     (obj_name cerb_frontend__String_defacto_memory)
     (visibility public)
     (impl))
    ((name String_mem)
     (obj_name cerb_frontend__String_mem)
     (visibility public)
     (impl))
    ((name String_nat_big_num)
     (obj_name cerb_frontend__String_nat_big_num)
     (visibility public)
     (impl)
     (intf))
    ((name String_symbol)
     (obj_name cerb_frontend__String_symbol)
     (visibility public)
     (impl))
    ((name Switches)
     (obj_name cerb_frontend__Switches)
     (visibility public)
     (impl)
     (intf))
    ((name Symbol)
     (obj_name cerb_frontend__Symbol)
     (visibility public)
     (impl))
    ((name Tags)
     (obj_name cerb_frontend__Tags)
     (visibility public)
     (impl)
     (intf))
    ((name Trace_event)
     (obj_name cerb_frontend__Trace_event)
     (visibility public)
     (impl))
    ((name Translation)
     (obj_name cerb_frontend__Translation)
     (visibility public)
     (impl))
    ((name Translation_aux)
     (obj_name cerb_frontend__Translation_aux)
     (visibility public)
     (impl))
    ((name Translation_effect)
     (obj_name cerb_frontend__Translation_effect)
     (visibility public)
     (impl))
    ((name TypingError)
     (obj_name cerb_frontend__TypingError)
     (visibility public)
     (impl))
    ((name Undefined)
     (obj_name cerb_frontend__Undefined)
     (visibility public)
     (impl))
    ((name Utils) (obj_name cerb_frontend__Utils) (visibility public) (impl))
    ((name Version)
     (obj_name cerb_frontend__Version)
     (visibility public)
     (impl))
    ((name WipFrontend)
     (obj_name cerb_frontend__WipFrontend)
     (visibility public)
     (impl)))
   (alias_module
    (name Cerb_frontend)
    (obj_name cerb_frontend)
    (visibility public)
    (kind alias)
    (impl))
   (wrapped true))))
(library
 (name cerberus.mem.concrete)
 (kind normal)
 (archives
  (byte mem/concrete/mem_concrete.cma)
  (native mem/concrete/mem_concrete.cmxa))
 (plugins
  (byte mem/concrete/mem_concrete.cma)
  (native mem/concrete/mem_concrete.cmxs))
 (native_archives mem/concrete/mem_concrete.a)
 (requires cerberus.frontend)
 (implements cerberus.frontend)
 (main_module_name Cerb_frontend)
 (modes byte native)
 (modules
  (wrapped
   (main_module_name Cerb_frontend)
   (modules
    ((name Impl_mem)
     (obj_name cerb_frontend__Impl_mem)
     (visibility public)
     (kind impl_vmodule)
     (impl)))
   (alias_module
    (name Cerb_frontend__mem_concrete__)
    (obj_name cerb_frontend__mem_concrete__)
    (visibility public)
    (kind alias)
    (impl))
   (wrapped true))))
(library
 (name cerberus.mem.symbolic)
 (kind normal)
 (archives
  (byte mem/symbolic/mem_symbolic.cma)
  (native mem/symbolic/mem_symbolic.cmxa))
 (plugins
  (byte mem/symbolic/mem_symbolic.cma)
  (native mem/symbolic/mem_symbolic.cmxs))
 (native_archives mem/symbolic/mem_symbolic.a)
 (requires cerberus.frontend z3)
 (implements cerberus.frontend)
 (main_module_name Cerb_frontend)
 (modes byte native)
 (obj_dir (private_dir .private))
 (modules
  (wrapped
   (main_module_name Cerb_frontend)
   (modules
    ((name Impl_mem)
     (obj_name cerb_frontend__Impl_mem)
     (visibility public)
     (kind impl_vmodule)
     (impl))
    ((name Mem_simplify)
     (obj_name cerb_frontend__mem_symbolic____Mem_simplify)
     (visibility private)
     (impl)))
   (alias_module
    (name Cerb_frontend__mem_symbolic__)
    (obj_name cerb_frontend__mem_symbolic__)
    (visibility public)
    (kind alias)
    (impl))
   (wrapped true))))
(library
 (name cerberus.sibylfs)
 (kind normal)
 (synopsis Sibylfs)
 (archives (byte sibylfs/sibylfs.cma) (native sibylfs/sibylfs.cmxa))
 (plugins (byte sibylfs/sibylfs.cma) (native sibylfs/sibylfs.cmxs))
 (native_archives sibylfs/sibylfs.a)
 (requires sha lem ppx_sexp_conv sexplib ppx_sexp_conv.runtime-lib)
 (modes byte native)
 (modules
  (unwrapped
   ((name Abstract_string)
    (obj_name abstract_string)
    (visibility public)
    (impl)
    (intf))
   ((name Dir_heap) (obj_name dir_heap) (visibility public) (impl))
   ((name Fs_dict_wrappers)
    (obj_name fs_dict_wrappers)
    (visibility public)
    (impl)
    (intf))
   ((name Fs_dump) (obj_name fs_dump) (visibility public) (impl))
   ((name Fs_prelude) (obj_name fs_prelude) (visibility public) (impl))
   ((name Fs_printer) (obj_name fs_printer) (visibility public) (impl))
   ((name Fs_spec) (obj_name fs_spec) (visibility public) (impl))
   ((name Lem_support)
    (obj_name lem_support)
    (visibility public)
    (impl)
    (intf))
   ((name List_array) (obj_name list_array) (visibility public) (impl))
   ((name Sibylfs) (obj_name sibylfs) (visibility public) (impl)))))
(library
 (name cerberus.util)
 (kind normal)
 (synopsis "Cerberus util library")
 (archives (byte util/util.cma) (native util/util.cmxa))
 (plugins (byte util/util.cma) (native util/util.cmxs))
 (native_archives util/util.a)
 (requires lem pprint yojson)
 (modes byte native)
 (modules
  (unwrapped
   ((name Cerb_runtime)
    (obj_name cerb_runtime)
    (visibility public)
    (impl)
    (intf))
   ((name Colour) (obj_name colour) (visibility public) (impl) (intf))
   ((name Debug_ocaml)
    (obj_name debug_ocaml)
    (visibility public)
    (impl)
    (intf))
   ((name Floating) (obj_name floating) (visibility public) (impl))
   ((name Fresh) (obj_name fresh) (visibility public) (impl))
   ((name Global_ocaml)
    (obj_name global_ocaml)
    (visibility public)
    (impl)
    (intf))
   ((name Json) (obj_name json) (visibility public) (impl))
   ((name Location_ocaml)
    (obj_name location_ocaml)
    (visibility public)
    (impl)
    (intf))
   ((name Logging) (obj_name logging) (visibility public) (impl) (intf))
   ((name N1570) (obj_name n1570) (visibility public) (impl))
   ((name Ocaml_any) (obj_name ocaml_any) (visibility public) (impl))
   ((name Pp_prelude) (obj_name pp_prelude) (visibility public) (impl) (intf))
   ((name Util) (obj_name util) (visibility public) (impl)))))
```

**Comment by rgrinberg** [comment]
Thanks. Unfortunately, I remain confused.

When I reproduced the bug with an older version of dune, I noticed that the `requires` field was missing for libraries with `implements`. Adding that missing field back fixed the problem, and recent versions of dune added the `requires` field correctly.

It seems like you're experiencing the same problem even when the `requires` field is set. Which is something I haven't reproduced myself :/

**Comment by rlepigre** [comment]
OK, so do you mean that everything should work with dune 2.7.0 or higher?
I'm currently creating a fresh opam switch to test things again, maybe I made a mistake in my previous attempts at testing (though I doubt it since I was careful).

**Comment by rlepigre** [comment]
I managed to reproduce the problem once again using the following procedure:
```bash
# Run the following in an initially empty directory.
$> opam switch create . ocaml-base-compiler.4.07.1
$> opam pin add -n -y cerberus git+https://github.com/rlepigre/cerberus.git
$> opam install dune.2.7.0 cerberus
$> wget https://github.com/ocaml/dune/files/4955076/buggy.tar.gz
$> tar xf buggy.tar.gz
$> cd buggy
$> dune build
File "main.ml", line 1, characters 5-18:
Error: Unbound module Cerb_frontend
```

**Comment by rgrinberg** [comment]
Okay, I'm able to reproduce. Thanks.

**Comment by vzaliva** [comment]
I am running into the same problem. The workaround suggested by @rlepigre to add `-I` flag:

```
 (flags (:standard -w -27 -I +../cerberus/frontend)) 
```

made it compile when invoking `dune`. However, in my emacs (using merlin) it still shows module import errors.

**Comment by vzaliva** [comment]
Merlin issue seems to be unrelated to this: https://github.com/ocaml/merlin/issues/1388
