### ISSUE TITLE
ci: regular failure of 4 tests

### ISSUE THREAD

**Issue by maiste** [ocaml/dune#11450]
Since the introduction of #11302, some tests seem to fail with the following errors:
```
Unbound module Mutex
```
This PR indeed introduces a call to a `Mutex` module in _vendor/opam-file-format_.

This issue concerns the following tests:
- Coq 8.16.1
- Wasm_of_ocaml
- Build monorepo benchmark docker image
- Build (ocaml-base-compiler.4.14.2,system-msvc, windows-latest

The common thing is that they all worked on `4.14.X`. However, I have check [in the manual](https://ocaml.org/manual/4.14/api/Mutex.html), the `module Mutex` is available.

Does it require to be added to the deps as Unix for this version? Any ideas about this @Leonidas-from-XIV, @gridbugs and @rgrinberg?

**Comment by gridbugs** [comment]
Regarding the monorepo benchmark, despite it failing on many PRs it does sometimes work (e.g. [here](https://bench.ci.dev/ocaml/dune/pull/11462/base/main?worker=fermat&image=bench%2Fmonorepo%2Fbench.Dockerfile)'s a successful run from today. It's also reliable when I [run it locally](https://github.com/ocaml/dune/blob/main/doc/dev/monorepo-bench.md#how-to-run-the-benchmarks-locally). Unfortunately when it fails the logs don't seem to get stored in current-bench (I'm asking around to see if there's a way to see the logs).
